# Generated by Django 6.0.7 on 2026-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='Book title', max_length=255, unique=True)),
                ('book_isbn', models.CharField(help_text='17 character International Standard Book Number', max_length=17, unique=True)),
            ],
        ),
    ]
