# Generated by Django 6.0.7 on 2026-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(help_text='Church Name', max_length=255)),
                ('church_times', models.CharField(max_length=255)),
            ],
        ),
    ]
