# Generated by Django 6.0.7 on 2026-07-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgagePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=200)),
                ('pool_number', models.CharField(max_length=200)),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
