# Generated by Django 6.0.7 on 2026-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_mortgagepool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIRRScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('coupon_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funding_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('servicing_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_margin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
